CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  username VARCHAR(255) NOT NULL UNIQUE,
  firstname VARCHAR(255) NOT NULL UNIQUE,
  lastname VARCHAR(255) NOT NULL UNIQUE,
  member BOOLEAN NOT NULL,
  admin BOOLEAN NOT NULL,
  hash TEXT NOT NULL,
  salt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS logs (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  posted TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  username VARCHAR(255) NOT NULL,
  message TEXT NOT NULL
);